# 剖析Promise内部结构
## 1.构造函数
```
// Promise构造函数接收一个executor函数，executor函数执行完同步或异步操作后，调用它的两个参数resolve和reject
var promise = new Promise(function(resolve,reject){
    /*
    如果操作成功，调用resolve并传入value
    如果操作失败，调用reject并传入reason
  */
})
```
实现构造函数的框架
```
function Promise(executor){
    var self = this;
    self.status = 'pending';//Promise当前的状态
    self.data = undefined;//Promise的值
    // Promise resolve时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
    self.onResolvedCallback = [];
    // Promise reject时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
    self.onRejectedCallback = [];

    executor(resolve,reject);//执行executor并传入相应的参数
}
```
构造函数里定义resolve和reject这两个函数：
```
function Promise(executor){
    var self = this;
    self.status = 'pending';//Promise当前的状态
    self.data = undefined;//Promise的值
    // Promise resolve时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
    self.onResolvedCallback = [];
    // Promise reject时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
    self.onRejectedCallback = [];

    function resolve(value){
        //TODO
    }

    function reject(reason){
        //TODO
    }

    // 考虑到执行executor的过程中有可能出错，所以我们用try/catch块给包起来，并且在出错后以catch到的值reject掉这个Promise
    try{
        executor(resolve,reject);//执行executor
    }catch(e){
        reject(e);
    }
}
```
实现resolve和reject这两个函数
```
function Promise(executor){
    //...

    function resolve(value){
        if(self.status === 'pending'){
            self.status = 'resolved';
            self.data = value;
            for(let i=0;i<self.onResolvedCallback.length;i++){
                self.onResolvedCallback[i](value);
            }
        }
    }

    function reject(reason){
        if(self.status === 'pending'){
            self.status = 'rejected';
            self.data = reason;
            for(let i=0;i<self.onRejectedCallback.length;i++){
                self.onRejectedCallback[i](reason);
            }
        }
    }

    //...
}
```

## 2.then方法
then方法会返回一个Promise  
实现then方法：
```
// then方法接收两个参数，onResolved，onRejected，分别为Promise成功或失败后的回调
Promise.prototype.then = function(onResolved,onRejected){
    var self = this;
    var promise2;

    // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理
    onResolved = typeof onResolved === 'function' ? onResolved : function(v){};
    onRejected = typeof onRejected === 'function' ? onRejected : function(r){};

    if(self.status === 'resolved'){
        return promise2 = new Promise(function(resolve,reject){

        })
    }

    if(self.status === 'rejected'){
        return promise2 = new Promise(function(resolve,reject){

        })
    }

    if(self.status === 'pending'){
        return promise2 = new Promise(function(resolve,reject){

        })
    }
}
```
我们需要在then里面执行onResolved或者onRejected，并根据返回值(标准中记为x)来确定promise2的结果，并且，如果onResolved/onRejected返回的是一个Promise，promise2将直接取这个Promise的结果：
```
Promise.prototype.then = function(onResolved,onRejected){
    var self = this;
    var promise2;

    // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理
    onResolved = typeof onResolved === 'function' ? onResolved : function(value) {}
    onRejected = typeof onRejected === 'function' ? onRejected : function(reason) {}

    if(self.status === 'resolved'){
        // 如果promise1(此处即为this/self)的状态已经确定并且是resolved，我们调用onResolved
        // 因为考虑到有可能throw，所以我们将其包在try/catch块里
        return promise2 = new Promise(function(resolve,reject){
            try {
                var x = onResolved(self.data);
                // 如果onResolved的返回值是一个Promise对象，直接取它的结果做为promise2的结果
                if (x instanceof Promise){
                    x.then(resolve,reject);
                }
                resolve(x);// 否则，以它的返回值做为promise2的结果
            }catch(e){
                reject(e);//如果出错，以捕获到的错误做为promise2的结果
            }
        })
    }

    // 此处与前一个if块的逻辑几乎相同，区别在于所调用的是onRejected函数，就不再做过多解释
    if(self.status === 'rejected'){
        return promise2 = new Promise(function(resolve,reject){
            try{
                var x = onRejected(self.data);
                if(x instanceof Promise){
                    x.then(resolve,reject);
                }
            }catch(e){
                reject(e);
            }
        })
    }

    if(self.status === 'pending'){
        // 如果当前的Promise还处于pending状态，我们并不能确定调用onResolved还是onRejected，
        // 只能等到Promise的状态确定后，才能确实如何处理。
        // 所以我们需要把我们的**两种情况**的处理逻辑做为callback放入promise1(此处即this/self)的回调数组里
        // 逻辑本身跟第一个if块内的几乎一致，此处不做过多解释
        return promise2 = new Promise(function(resolve,reject){
            self.onResolvedCallback.push(function(value){
                try{
                    var x = onResolved(self.data);
                    if(x instanceof Promise){
                        x.then(resolve,reject);
                    }
                }catch(e){
                    reject(e);
                }
            })

            self.onRejectedCallback.push(function(reason){
                try{
                    var x = onRejected(self.data);
                    if(x instanceof Promise){
                        x.then(resolve,reject);
                    }
                }catch(e){
                    reject(e);
                }
            })
        })
    }
}

Promise.prototype.catch = function(onRejected){
    return this.then(null,onRejected);
}
```

## 值的穿透
### Promise值的穿透
```
new Promise(resolve=>resolve(8)).then().catch().then(function(value){
    alert(value)
})
```
跟下面这段代码的行为是一样的
```
new Promise(resolve=>resolve(8)).then(function(value){
    return value;
}).catch(function(reason){
    throw reason;
}).then(function(value){
    alert(value);
})
```
所以如果想要把then的实参留空且让值可以穿透到后面，意味着then的两个参数的默认值分别为function(value) {return value}，function(reason) {throw reason}。
所以我们只需要把then里判断onResolved和onRejected的部分改成如下即可：
```
onResolved = typeof onResolved === 'function' ? onResolved : function(value){return value;};
onRejected = typeof onRejected === 'function' ? onRejected : function(reason) {throw reason;}
```
于是Promise神奇的值的穿透也没有那么黑魔法，只不过是then默认参数就是把值往后传或者抛

## 完整的Promise
```
try {
  module.exports = Promise
} catch (e) {}

function Promise(executor) {
  var self = this

  self.status = 'pending'
  self.onResolvedCallback = []
  self.onRejectedCallback = []

  function resolve(value) {
    if (value instanceof Promise) {
      return value.then(resolve, reject)
    }
    setTimeout(function() { // 异步执行所有的回调函数
      if (self.status === 'pending') {
        self.status = 'resolved'
        self.data = value
        for (var i = 0; i < self.onResolvedCallback.length; i++) {
          self.onResolvedCallback[i](value)
        }
      }
    })
  }

  function reject(reason) {
    setTimeout(function() { // 异步执行所有的回调函数
      if (self.status === 'pending') {
        self.status = 'rejected'
        self.data = reason
        for (var i = 0; i < self.onRejectedCallback.length; i++) {
          self.onRejectedCallback[i](reason)
        }
      }
    })
  }

  try {
    executor(resolve, reject)
  } catch (reason) {
    reject(reason)
  }
}

function resolvePromise(promise2, x, resolve, reject) {
  var then
  var thenCalledOrThrow = false

  if (promise2 === x) {
    return reject(new TypeError('Chaining cycle detected for promise!'))
  }

  if (x instanceof Promise) {
    if (x.status === 'pending') { //because x could resolved by a Promise Object
      x.then(function(v) {
        resolvePromise(promise2, v, resolve, reject)
      }, reject)
    } else { //but if it is resolved, it will never resolved by a Promise Object but a static value;
      x.then(resolve, reject)
    }
    return
  }

  if ((x !== null) && ((typeof x === 'object') || (typeof x === 'function'))) {
    try {
      then = x.then //because x.then could be a getter
      if (typeof then === 'function') {
        then.call(x, function rs(y) {
          if (thenCalledOrThrow) return
          thenCalledOrThrow = true
          return resolvePromise(promise2, y, resolve, reject)
        }, function rj(r) {
          if (thenCalledOrThrow) return
          thenCalledOrThrow = true
          return reject(r)
        })
      } else {
        resolve(x)
      }
    } catch (e) {
      if (thenCalledOrThrow) return
      thenCalledOrThrow = true
      return reject(e)
    }
  } else {
    resolve(x)
  }
}

Promise.prototype.then = function(onResolved, onRejected) {
  var self = this
  var promise2
  onResolved = typeof onResolved === 'function' ? onResolved : function(v) {
    return v
  }
  onRejected = typeof onRejected === 'function' ? onRejected : function(r) {
    throw r
  }

  if (self.status === 'resolved') {
    return promise2 = new Promise(function(resolve, reject) {
      setTimeout(function() { // 异步执行onResolved
        try {
          var x = onResolved(self.data)
          resolvePromise(promise2, x, resolve, reject)
        } catch (reason) {
          reject(reason)
        }
      })
    })
  }

  if (self.status === 'rejected') {
    return promise2 = new Promise(function(resolve, reject) {
      setTimeout(function() { // 异步执行onRejected
        try {
          var x = onRejected(self.data)
          resolvePromise(promise2, x, resolve, reject)
        } catch (reason) {
          reject(reason)
        }
      })
    })
  }

  if (self.status === 'pending') {
    // 这里之所以没有异步执行，是因为这些函数必然会被resolve或reject调用，而resolve或reject函数里的内容已是异步执行，构造函数里的定义
    return promise2 = new Promise(function(resolve, reject) {
      self.onResolvedCallback.push(function(value) {
        try {
          var x = onResolved(value)
          resolvePromise(promise2, x, resolve, reject)
        } catch (r) {
          reject(r)
        }
      })

      self.onRejectedCallback.push(function(reason) {
          try {
            var x = onRejected(reason)
            resolvePromise(promise2, x, resolve, reject)
          } catch (r) {
            reject(r)
          }
        })
    })
  }
}

Promise.prototype.catch = function(onRejected) {
  return this.then(null, onRejected)
}

Promise.deferred = Promise.defer = function() {
  var dfd = {}
  dfd.promise = new Promise(function(resolve, reject) {
    dfd.resolve = resolve
    dfd.reject = reject
  })
  return dfd
}
```